# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pando < Formula
  desc "Pando — encrypted peer-to-peer chat"
  homepage "https://github.com/elpdev/pando"
  version "0.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/pando/releases/download/v0.13.1/pando_0.13.1_darwin_amd64.tar.gz"
      sha256 "e8ad52bc727294d0396316174e527fd1c91baded71a4418c3c03d5792b422d58"

      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/pando/releases/download/v0.13.1/pando_0.13.1_darwin_arm64.tar.gz"
      sha256 "9e008e67b17a1890f947489805426dc9afc5b347a231c7348dc3eaf173da8a2e"

      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/pando/releases/download/v0.13.1/pando_0.13.1_linux_amd64.tar.gz"
      sha256 "166bc159790709808f7358515ad80bf70f7a361dcc6010cc7afa1965299b3d22"
      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/pando/releases/download/v0.13.1/pando_0.13.1_linux_arm64.tar.gz"
      sha256 "afff6ca1a0ba2d7c246fcfeff049a0a7524be69452a92bd2e0ba04b03ee106ff"
      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
  end
end
