# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pando < Formula
  desc "Pando — encrypted peer-to-peer chat"
  homepage "https://github.com/elpdev/pando"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/pando/releases/download/v0.13.0/pando_0.13.0_darwin_amd64.tar.gz"
      sha256 "b70296cccf13bd3e9928c499ae1c09a6b5fc815d2e55c12b39a3f03bdc7a18d0"

      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/pando/releases/download/v0.13.0/pando_0.13.0_darwin_arm64.tar.gz"
      sha256 "db533dd248e0abcdbcb05552e0584fa0ba696f13c3b62e0f252fb8d51089273d"

      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/pando/releases/download/v0.13.0/pando_0.13.0_linux_amd64.tar.gz"
      sha256 "5340136703c67102f8e73e1ff8e629830884abb429cd0e980d297ddbbf78cd76"
      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/pando/releases/download/v0.13.0/pando_0.13.0_linux_arm64.tar.gz"
      sha256 "a6c0b56863f15430d8938db8610651ff6e70d06ed5a7170586a7a83114c06041"
      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
  end
end
