# This file was generated by GoReleaser. DO NOT EDIT.
cask "orange_clown" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/elpdev/orange_clown-cli/releases/download/v#{version}/orange_clown_#{version}_darwin_amd64.tar.gz"
      sha256 "4c18c1ba8fb58378c4962117bc9a5519926c66f4d947d697339fb2b6d5cdcbe2"
    end
    on_arm do
      url "https://github.com/elpdev/orange_clown-cli/releases/download/v#{version}/orange_clown_#{version}_darwin_arm64.tar.gz"
      sha256 "4bf4b6219e752399a2c29d19e33ccc8d305456ba2d16eb658b0f87f93a31f2fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elpdev/orange_clown-cli/releases/download/v#{version}/orange_clown_#{version}_linux_amd64.tar.gz"
      sha256 "726c2808a0885731d7e0148d646fbeb9e0621d3fd7b94ff99910b76a73f7a3ab"
    end
    on_arm do
      url "https://github.com/elpdev/orange_clown-cli/releases/download/v#{version}/orange_clown_#{version}_linux_arm64.tar.gz"
      sha256 "7b02b8c49f6d78c576a8b2c1e3f0d8784d869cdaa6f3f9cf6bd18833469f4dd1"
    end
  end

  name "orange_clown"
  desc "Orange Clown CLI - manage articles, feeds, newsletters, and newsroom automation from the terminal"
  homepage "https://github.com/elpdev/orange_clown-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orange_clown"

  # No zap stanza required

end
