# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bubbleplate < Formula
  desc "Opinionated generator for Go terminal UI projects built with the Charm stack"
  homepage "https://github.com/elpdev/bubbleplate"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/bubbleplate/releases/download/v0.3.0/bubbleplate_0.3.0_darwin_amd64.tar.gz"
      sha256 "9db39de07e77fed27beafa9f6626209bcbe41caa7784df9ef9e0f1e47e336360"

      define_method(:install) do
        bin.install "bubbleplate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/bubbleplate/releases/download/v0.3.0/bubbleplate_0.3.0_darwin_arm64.tar.gz"
      sha256 "837977af7eb0e553f59daa729de4002176ba43b32bb1c9cb7e062f87c30c5105"

      define_method(:install) do
        bin.install "bubbleplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/bubbleplate/releases/download/v0.3.0/bubbleplate_0.3.0_linux_amd64.tar.gz"
      sha256 "837405b6d4a35ab8597065fcbf597e203ba4e47af0de601658390c13525c7a28"
      define_method(:install) do
        bin.install "bubbleplate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/bubbleplate/releases/download/v0.3.0/bubbleplate_0.3.0_linux_arm64.tar.gz"
      sha256 "a239ac2efa776418b25d0765a4210548309edc0ebb4d9057e6de479fab2922be"
      define_method(:install) do
        bin.install "bubbleplate"
      end
    end
  end
end
