# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bubbleplate < Formula
  desc "Opinionated generator for Go terminal UI projects built with the Charm stack"
  homepage "https://github.com/elpdev/bubbleplate"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/bubbleplate/releases/download/v0.4.0/bubbleplate_0.4.0_darwin_amd64.tar.gz"
      sha256 "d2d8a6b50b01db8f452e20cf19c7a543b0abcf637c76bab4e75d8db622b202cf"

      define_method(:install) do
        bin.install "bubbleplate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/bubbleplate/releases/download/v0.4.0/bubbleplate_0.4.0_darwin_arm64.tar.gz"
      sha256 "1a0cec27989806f93bcb283b002f622f8cbe63dad906bb643f390b1473d3d6bb"

      define_method(:install) do
        bin.install "bubbleplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/bubbleplate/releases/download/v0.4.0/bubbleplate_0.4.0_linux_amd64.tar.gz"
      sha256 "96aed6626771ed64b9c6ce3478fba9348d355daef1eb1570b348bf19ce7a9de1"
      define_method(:install) do
        bin.install "bubbleplate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/bubbleplate/releases/download/v0.4.0/bubbleplate_0.4.0_linux_arm64.tar.gz"
      sha256 "cb01f698505ffa4e7197b9f3c1adf075831c487961a864c40bb001f42310fada"
      define_method(:install) do
        bin.install "bubbleplate"
      end
    end
  end
end
