# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ContentFoundry < Formula
  desc "Content Foundry CLI - manage your content pipeline from the terminal"
  homepage "https://github.com/elpdev/content_foundry-cli"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/content_foundry-cli/releases/download/v0.1.6/content_foundry_0.1.6_darwin_amd64.tar.gz"
      sha256 "340037a62c07eeea9f4fe0137a3932e1b9c7b27015671bada49f4b0929357cee"

      define_method(:install) do
        bin.install "content_foundry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/content_foundry-cli/releases/download/v0.1.6/content_foundry_0.1.6_darwin_arm64.tar.gz"
      sha256 "b68e8e1356ffd545ea01bd4e8f3c6b9864f4b84e239a750934a4e5261bc616b7"

      define_method(:install) do
        bin.install "content_foundry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/content_foundry-cli/releases/download/v0.1.6/content_foundry_0.1.6_linux_amd64.tar.gz"
      sha256 "d74ff75ccc2f7214d62a6afb4573c02cdbc294f6ee69d81eb5a60cab878db017"
      define_method(:install) do
        bin.install "content_foundry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/content_foundry-cli/releases/download/v0.1.6/content_foundry_0.1.6_linux_arm64.tar.gz"
      sha256 "35ab15e44c7243d1be24405e3bf68b50de318af9968d50fde2caf35ba903a312"
      define_method(:install) do
        bin.install "content_foundry"
      end
    end
  end

  test do
    assert_match "CONTENT FOUNDRY", shell_output("#{bin}/content_foundry --help")
  end
end
