# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ContentFoundry < Formula
  desc "Content Foundry CLI - manage your content pipeline from the terminal"
  homepage "https://github.com/elpdev/content_foundry-cli"
  version "0.1.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/content_foundry-cli/releases/download/v0.1.12/content_foundry_0.1.12_darwin_amd64.tar.gz"
      sha256 "d14bf78e2722dd83d554ce7d460dd9a83a32fcf6e36904ebf56a48b9a94b5beb"

      define_method(:install) do
        bin.install "content_foundry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/content_foundry-cli/releases/download/v0.1.12/content_foundry_0.1.12_darwin_arm64.tar.gz"
      sha256 "43d654afa6162e913b822541ffb490e5d114eeb1e853fe7ec2908efc8fbbe31f"

      define_method(:install) do
        bin.install "content_foundry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/content_foundry-cli/releases/download/v0.1.12/content_foundry_0.1.12_linux_amd64.tar.gz"
      sha256 "84209c104f0f779cdd5dc773b71baa59c706d01f7fd7c4612d9bcd17b4383406"
      define_method(:install) do
        bin.install "content_foundry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/content_foundry-cli/releases/download/v0.1.12/content_foundry_0.1.12_linux_arm64.tar.gz"
      sha256 "b3b0ac94a4ff5a77cfd6a738d3b4c793b7b6ba7c45cb68780ca2f253522732cf"
      define_method(:install) do
        bin.install "content_foundry"
      end
    end
  end

  test do
    assert_match "CONTENT FOUNDRY", shell_output("#{bin}/content_foundry --help")
  end
end
