# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrangeClown < Formula
  desc "Orange Clown CLI - manage articles, feeds, newsletters, and newsroom automation from the terminal"
  homepage "https://github.com/elpdev/orange_clown-cli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/orange_clown-cli/releases/download/v0.1.2/orange_clown_0.1.2_darwin_amd64.tar.gz"
      sha256 "befd3c6c165238c24a77fca7bed749393d5ebf25ad3b9126dc2dad70d1f9d808"

      define_method(:install) do
        bin.install "orange_clown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/orange_clown-cli/releases/download/v0.1.2/orange_clown_0.1.2_darwin_arm64.tar.gz"
      sha256 "9656eff284e98d5c5d3ce25b616b444df14fa3fd02658f033850cbf845fdc384"

      define_method(:install) do
        bin.install "orange_clown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/orange_clown-cli/releases/download/v0.1.2/orange_clown_0.1.2_linux_amd64.tar.gz"
      sha256 "6eb8bf4880147657a3fa8b6eec28526875aa662ec5a6375dee4e026933d756ee"
      define_method(:install) do
        bin.install "orange_clown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/orange_clown-cli/releases/download/v0.1.2/orange_clown_0.1.2_linux_arm64.tar.gz"
      sha256 "8c49bd883ee12b9f8f65325f336361bfbfeb34ab962065c23f2e82b7fcc36042"
      define_method(:install) do
        bin.install "orange_clown"
      end
    end
  end
end
