# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pando < Formula
  desc "Pando — end-to-end encrypted chat over self-hosted relays"
  homepage "https://github.com/elpdev/pando"
  version "0.29.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/pando/releases/download/v0.29.2/pando_0.29.2_darwin_amd64.tar.gz"
      sha256 "7150c20c225fe6c89976df97a82fa5b487e45b3f0a9a612f221e67b117462a0a"

      define_method(:install) do
        bin.install "pando"
        bin.install "pando-relay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/pando/releases/download/v0.29.2/pando_0.29.2_darwin_arm64.tar.gz"
      sha256 "68ce132109a4b16760333c146ccb39b0f03777ff2abeaf507ae73f3e01ce79e1"

      define_method(:install) do
        bin.install "pando"
        bin.install "pando-relay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/pando/releases/download/v0.29.2/pando_0.29.2_linux_amd64.tar.gz"
      sha256 "8c98e5998db716280f354817b05552aca0c976e224a910f294343f003a746fa5"
      define_method(:install) do
        bin.install "pando"
        bin.install "pando-relay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/pando/releases/download/v0.29.2/pando_0.29.2_linux_arm64.tar.gz"
      sha256 "0acb179c68392a32a44a228175047fc9d41ef709e560e0bb7823023e3218fa0a"
      define_method(:install) do
        bin.install "pando"
        bin.install "pando-relay"
      end
    end
  end
end
