# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pando < Formula
  desc "Pando — end-to-end encrypted chat over self-hosted relays"
  homepage "https://github.com/elpdev/pando"
  version "0.15.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/pando/releases/download/v0.15.3/pando_0.15.3_darwin_amd64.tar.gz"
      sha256 "3390487eb9ff538558125d2640ab11815246a2106e79efe1571689741f65f758"

      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/pando/releases/download/v0.15.3/pando_0.15.3_darwin_arm64.tar.gz"
      sha256 "963b3614628d56fe2c604b272703f69c68757343d0e2a1ce390b7c86c27b0cda"

      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/pando/releases/download/v0.15.3/pando_0.15.3_linux_amd64.tar.gz"
      sha256 "8c03195374ccd4483b85ae8282f57f6d4f648abd557591ab784d2957b55ecc5d"
      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/pando/releases/download/v0.15.3/pando_0.15.3_linux_arm64.tar.gz"
      sha256 "2938a63fef6e45e2c4e5034a0232acac13177ada7295ce00644c9496742f7481"
      define_method(:install) do
        bin.install "pando"
        bin.install "pandoctl"
        bin.install "pando-relay"
      end
    end
  end
end
