# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Telex < Formula
  desc "Telex CLI for terminal-first workflows"
  homepage "https://github.com/elpdev/telex-cli"
  version "0.1.21"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.21/telex_0.1.21_darwin_amd64.tar.gz"
      sha256 "7618f328326d4fe09d2c872e5e2354995514fb3758695cfe6a1c1ef4020e336b"

      define_method(:install) do
        bin.install "telex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.21/telex_0.1.21_darwin_arm64.tar.gz"
      sha256 "bac152f1627b5a6626597b16d9cc6140c8ed1aaa9752306c82d2e507cd9eb46b"

      define_method(:install) do
        bin.install "telex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.21/telex_0.1.21_linux_amd64.tar.gz"
      sha256 "afa96606d8663860159184425782a52c0fea0ee34bb79a6724b45e1a578f12fd"
      define_method(:install) do
        bin.install "telex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.21/telex_0.1.21_linux_arm64.tar.gz"
      sha256 "669b1815bba3d55ad52cb986958b1e27060eb544436c5d58ca8e8b2fe5756d0a"
      define_method(:install) do
        bin.install "telex"
      end
    end
  end

  test do
    assert_match "Telex CLI", shell_output("#{bin}/telex --help")
  end
end
