# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Telex < Formula
  desc "Telex CLI for terminal-first workflows"
  homepage "https://github.com/elpdev/telex-cli"
  version "0.1.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.15/telex_0.1.15_darwin_amd64.tar.gz"
      sha256 "45e7a8dccf9c1a58b54c87b439e33e4c9fb9a0d463d6cb4567badd9e9cb83f1a"

      define_method(:install) do
        bin.install "telex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.15/telex_0.1.15_darwin_arm64.tar.gz"
      sha256 "eae1be3554da721ac0113326fce4dcc56257074a1e1d5236a1bf2161d790d35f"

      define_method(:install) do
        bin.install "telex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.15/telex_0.1.15_linux_amd64.tar.gz"
      sha256 "ae0fb88bfd767dcf6b3c3ae22c914e2525be4268677230124a7ed762de18fff1"
      define_method(:install) do
        bin.install "telex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.15/telex_0.1.15_linux_arm64.tar.gz"
      sha256 "e1b1aeea62d02e4acdd17090e970987846fffedddd6bf3824c604592f02c3f4a"
      define_method(:install) do
        bin.install "telex"
      end
    end
  end

  test do
    assert_match "Telex CLI", shell_output("#{bin}/telex --help")
  end
end
