# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Telex < Formula
  desc "Telex CLI for terminal-first workflows"
  homepage "https://github.com/elpdev/telex-cli"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.6/telex_0.1.6_darwin_amd64.tar.gz"
      sha256 "f603bcf8205b999b178bb9328319548afcafc9f06bf8b7ff9a5fec89478bf5d4"

      define_method(:install) do
        bin.install "telex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.6/telex_0.1.6_darwin_arm64.tar.gz"
      sha256 "6bbb6217ebad5648b94d85f151ded1e065302977996b986a0d1cd63e8a60c079"

      define_method(:install) do
        bin.install "telex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.6/telex_0.1.6_linux_amd64.tar.gz"
      sha256 "3047c8aa7222a2d9bc0a8b7eb1238d8be2d6dd3bd0c87badfbb5e9fb9110f8c8"
      define_method(:install) do
        bin.install "telex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elpdev/telex-cli/releases/download/v0.1.6/telex_0.1.6_linux_arm64.tar.gz"
      sha256 "f17a5d9c931c12bea9146e72e5fe341835dd6a8b5d9371181fc512bb961bf1f0"
      define_method(:install) do
        bin.install "telex"
      end
    end
  end

  test do
    assert_match "Telex CLI", shell_output("#{bin}/telex --help")
  end
end
